### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [AUcod3r/aurulz#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by AUcod3r** [comment]
Hey Ken!  I added the meta viewport tag, it looks good on my droid, how about now on your device?

**Comment by kenmazaika** [comment]
Thumbs up!  Solid work! :)  :+1:
